name = "vnbway-api"
main = "src/index.ts"
compatibility_date = "2026-04-03"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "vnbway-media"

[vars]
FRONTEND_ORIGIN = "https://www.vnbway.com"
PAYSTACK_CURRENCY = "GHS"
PAYSTACK_CHANNELS = "card,mobile_money,bank_transfer"
