-- VNB Supabase schema (core objects only)
-- Run this first.

create extension if not exists pgcrypto;

create or replace function public.now_utc()
returns timestamptz
language sql
stable
as $$
  select timezone('utc', now());
$$;

create or replace function public.generate_order_number()
returns text
language sql
stable
as $$
  select 'VNB-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = public.now_utc();
  return new;
end;
$$;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text not null default '',
  image_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete cascade,
  name text not null,
  slug text not null unique,
  description text not null default '',
  price numeric(10, 2) not null check (price >= 0),
  image_url text,
  is_active boolean not null default true,
  is_featured boolean not null default false,
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  sku text unique,
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image_url text not null,
  alt_text text not null default '',
  is_primary boolean not null default false,
  "order" integer not null default 0,
  created_at timestamptz not null default public.now_utc()
);

create table if not exists public.product_colors (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  name text not null,
  hex_code text not null,
  is_available boolean not null default true,
  unique(product_id, name)
);

create table if not exists public.product_sizes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  size text not null,
  is_available boolean not null default true,
  unique(product_id, size)
);

create table if not exists public.product_details (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  detail text not null,
  "order" integer not null default 0
);

create table if not exists public.newsletters (
  id bigint generated by default as identity primary key,
  email text not null unique,
  subscribed_at timestamptz not null default public.now_utc(),
  is_active boolean not null default true
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null default '',
  subject text not null,
  message text not null,
  created_at timestamptz not null default public.now_utc(),
  is_read boolean not null default false
);

create table if not exists public.investment_inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  tier text not null check (tier in ('seed', 'growth', 'strategic', 'custom')),
  message text not null default '',
  created_at timestamptz not null default public.now_utc(),
  is_contacted boolean not null default false
);

create table if not exists public.user_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  title text not null default '',
  phone text not null default '',
  area_code text not null default '+1',
  birth_date date,
  company text not null default '',
  address text not null default '',
  address_continued text not null default '',
  city text not null default '',
  state text not null default '',
  zip_code text not null default '',
  zip_plus text not null default '',
  location text not null default 'United States',
  newsletter_subscribed boolean not null default false,
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

create table if not exists public.carts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  session_key text not null default '',
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  cart_id bigint not null references public.carts(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  size text not null default '',
  color text not null default '',
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc(),
  unique(cart_id, product_id, size, color)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  order_number text not null unique default public.generate_order_number(),
  email text not null,
  first_name text not null,
  last_name text not null,
  phone text not null,
  address text not null,
  city text not null,
  state text not null,
  zip_code text not null,
  country text not null,
  subtotal numeric(10, 2) not null,
  shipping numeric(10, 2) not null default 0,
  tax numeric(10, 2) not null default 0,
  total numeric(10, 2) not null,
  status text not null default 'pending' check (status in ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
  payment_provider text not null default '',
  payment_reference text unique,
  payment_currency text not null default 'USD',
  payment_status text not null default 'pending' check (payment_status in ('pending', 'paid', 'failed')),
  paid_at timestamptz,
  notes text not null default '',
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  product_sku text not null default '',
  quantity integer not null check (quantity > 0),
  size text not null default '',
  color text not null default '',
  price numeric(10, 2) not null,
  subtotal numeric(10, 2) not null
);

create table if not exists public.payment_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  order_id bigint unique references public.orders(id) on delete set null,
  reference text not null unique,
  access_code text not null default '',
  authorization_url text not null default '',
  email text not null,
  first_name text not null,
  last_name text not null,
  phone text not null,
  address text not null,
  city text not null,
  state text not null,
  zip_code text not null,
  country text not null,
  notes text not null default '',
  subtotal numeric(10, 2) not null,
  shipping numeric(10, 2) not null default 0,
  tax numeric(10, 2) not null default 0,
  total numeric(10, 2) not null,
  currency text not null default 'USD',
  status text not null default 'initialized' check (status in ('initialized', 'pending', 'success', 'failed')),
  paystack_status text not null default '',
  cart_snapshot jsonb not null default '[]'::jsonb,
  cart_item_ids jsonb not null default '[]'::jsonb,
  verified_at timestamptz,
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default public.now_utc()
);

create or replace function public.is_admin(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.admin_users where user_id = uid);
$$;

create index if not exists idx_products_category_active on public.products(category_id, is_active);
create index if not exists idx_products_slug on public.products(slug);
create index if not exists idx_orders_user on public.orders(user_id);
create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_contact_messages_created_at on public.contact_messages(created_at desc);
create index if not exists idx_investment_inquiries_created_at on public.investment_inquiries(created_at desc);

drop trigger if exists trg_categories_updated_at on public.categories;
create trigger trg_categories_updated_at before update on public.categories
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_products_updated_at on public.products;
create trigger trg_products_updated_at before update on public.products
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_user_profiles_updated_at on public.user_profiles;
create trigger trg_user_profiles_updated_at before update on public.user_profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_carts_updated_at on public.carts;
create trigger trg_carts_updated_at before update on public.carts
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_cart_items_updated_at on public.cart_items;
create trigger trg_cart_items_updated_at before update on public.cart_items
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at before update on public.orders
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_payment_attempts_updated_at on public.payment_attempts;
create trigger trg_payment_attempts_updated_at before update on public.payment_attempts
for each row execute procedure public.set_updated_at();
