-- VNB Steward / affiliate module
-- Run after 01_core.sql, 02_rls.sql, and 03_checkout.sql

create table if not exists public.steward_waitlist (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null unique,
  phone text not null default '',
  location text not null default '',
  background text not null default '',
  message text not null default '',
  status text not null default 'joined' check (status in ('joined', 'reviewed', 'invited', 'archived')),
  converted_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

create table if not exists public.vnb_stewards (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  status text not null default 'waitlisted' check (status in ('waitlisted', 'invited', 'active', 'paused', 'suspended', 'removed')),
  commission_tier text not null default 'standard' check (commission_tier in ('standard', 'support')),
  commission_rate numeric(5, 4) not null default 0.1000 check (commission_rate >= 0 and commission_rate <= 1),
  course_status text not null default 'not_started' check (course_status in ('not_started', 'in_progress', 'completed', 'waived')),
  payout_method text not null default '',
  payout_account_ref text not null default '',
  notes text not null default '',
  joined_at timestamptz not null default public.now_utc(),
  activated_at timestamptz,
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

create table if not exists public.steward_referral_codes (
  id bigint generated by default as identity primary key,
  steward_id uuid not null references public.vnb_stewards(user_id) on delete cascade,
  code text not null unique,
  status text not null default 'active' check (status in ('active', 'inactive', 'expired')),
  is_primary boolean not null default false,
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

create unique index if not exists idx_steward_referral_codes_primary
on public.steward_referral_codes (steward_id)
where is_primary = true;

create table if not exists public.steward_payouts (
  id bigint generated by default as identity primary key,
  steward_id uuid not null references public.vnb_stewards(user_id) on delete cascade,
  period_start date not null,
  period_end date not null,
  scheduled_for date,
  gross_commission numeric(10, 2) not null default 0,
  adjustments numeric(10, 2) not null default 0,
  total_amount numeric(10, 2) not null default 0,
  status text not null default 'pending' check (status in ('pending', 'processing', 'paid', 'failed', 'cancelled')),
  payout_reference text not null default '',
  notes text not null default '',
  paid_at timestamptz,
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

create table if not exists public.steward_commissions (
  id bigint generated by default as identity primary key,
  steward_id uuid not null references public.vnb_stewards(user_id) on delete cascade,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  payout_id bigint references public.steward_payouts(id) on delete set null,
  referral_code text not null default '',
  basis_amount numeric(10, 2) not null default 0,
  commission_rate numeric(5, 4) not null check (commission_rate >= 0 and commission_rate <= 1),
  commission_amount numeric(10, 2) not null default 0,
  status text not null default 'pending' check (status in ('pending', 'approved', 'paid', 'reversed', 'void')),
  notes text not null default '',
  approved_at timestamptz,
  paid_at timestamptz,
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

create table if not exists public.steward_milestone_definitions (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text not null default '',
  measurement_window text not null default 'weekly' check (measurement_window in ('weekly', 'all_time')),
  required_successful_orders integer not null check (required_successful_orders > 0),
  reward_type text not null default 'recognition' check (reward_type in ('recognition', 'store_credit', 'free_product', 'merchandise', 'ambassador_review')),
  reward_value text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

create table if not exists public.steward_milestone_awards (
  id bigint generated by default as identity primary key,
  steward_id uuid not null references public.vnb_stewards(user_id) on delete cascade,
  milestone_id bigint not null references public.steward_milestone_definitions(id) on delete cascade,
  reward_status text not null default 'pending' check (reward_status in ('pending', 'issued', 'redeemed', 'cancelled')),
  reference_period_start date,
  reference_period_end date,
  notes text not null default '',
  earned_at timestamptz not null default public.now_utc(),
  issued_at timestamptz,
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

create table if not exists public.steward_reward_ledger (
  id bigint generated by default as identity primary key,
  steward_id uuid not null references public.vnb_stewards(user_id) on delete cascade,
  source_type text not null default 'manual' check (source_type in ('manual', 'milestone', 'commission_adjustment', 'campaign')),
  source_id bigint,
  reward_type text not null check (reward_type in ('store_credit', 'free_product', 'recognition', 'merchandise', 'ambassador_access')),
  amount numeric(10, 2),
  currency text not null default 'GHS',
  description text not null default '',
  status text not null default 'pending' check (status in ('pending', 'issued', 'redeemed', 'cancelled')),
  fulfilled_at timestamptz,
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

alter table public.payment_attempts
  add column if not exists steward_id uuid references public.vnb_stewards(user_id) on delete set null,
  add column if not exists referral_code text not null default '',
  add column if not exists referral_snapshot jsonb not null default '{}'::jsonb;

alter table public.orders
  add column if not exists steward_id uuid references public.vnb_stewards(user_id) on delete set null,
  add column if not exists referral_code text not null default '',
  add column if not exists referral_snapshot jsonb not null default '{}'::jsonb,
  add column if not exists commissionable_subtotal numeric(10, 2) not null default 0;

create or replace function public.normalize_referral_code(p_code text)
returns text
language sql
immutable
as $$
  select upper(regexp_replace(coalesce(trim(p_code), ''), '[^A-Za-z0-9_-]', '', 'g'));
$$;

create or replace function public.prepare_steward_referral_code()
returns trigger
language plpgsql
as $$
begin
  new.code := public.normalize_referral_code(new.code);
  return new;
end;
$$;

drop trigger if exists trg_steward_waitlist_updated_at on public.steward_waitlist;
create trigger trg_steward_waitlist_updated_at before update on public.steward_waitlist
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_vnb_stewards_updated_at on public.vnb_stewards;
create trigger trg_vnb_stewards_updated_at before update on public.vnb_stewards
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_steward_referral_codes_updated_at on public.steward_referral_codes;
create trigger trg_steward_referral_codes_updated_at before update on public.steward_referral_codes
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_steward_referral_codes_prepare on public.steward_referral_codes;
create trigger trg_steward_referral_codes_prepare before insert or update on public.steward_referral_codes
for each row execute procedure public.prepare_steward_referral_code();

drop trigger if exists trg_steward_payouts_updated_at on public.steward_payouts;
create trigger trg_steward_payouts_updated_at before update on public.steward_payouts
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_steward_commissions_updated_at on public.steward_commissions;
create trigger trg_steward_commissions_updated_at before update on public.steward_commissions
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_steward_milestone_definitions_updated_at on public.steward_milestone_definitions;
create trigger trg_steward_milestone_definitions_updated_at before update on public.steward_milestone_definitions
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_steward_milestone_awards_updated_at on public.steward_milestone_awards;
create trigger trg_steward_milestone_awards_updated_at before update on public.steward_milestone_awards
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_steward_reward_ledger_updated_at on public.steward_reward_ledger;
create trigger trg_steward_reward_ledger_updated_at before update on public.steward_reward_ledger
for each row execute procedure public.set_updated_at();

create index if not exists idx_steward_waitlist_created_at on public.steward_waitlist(created_at desc);
create index if not exists idx_vnb_stewards_status on public.vnb_stewards(status);
create index if not exists idx_steward_referral_codes_code on public.steward_referral_codes(code);
create index if not exists idx_payment_attempts_steward_id on public.payment_attempts(steward_id);
create index if not exists idx_orders_steward_id on public.orders(steward_id);
create index if not exists idx_steward_commissions_steward_id on public.steward_commissions(steward_id, created_at desc);
create index if not exists idx_steward_payouts_steward_id on public.steward_payouts(steward_id, period_end desc);

alter table public.steward_waitlist enable row level security;
alter table public.vnb_stewards enable row level security;
alter table public.steward_referral_codes enable row level security;
alter table public.steward_payouts enable row level security;
alter table public.steward_commissions enable row level security;
alter table public.steward_milestone_definitions enable row level security;
alter table public.steward_milestone_awards enable row level security;
alter table public.steward_reward_ledger enable row level security;

drop policy if exists "public insert steward_waitlist" on public.steward_waitlist;
create policy "public insert steward_waitlist" on public.steward_waitlist
for insert with check (true);

drop policy if exists "public read active steward milestones" on public.steward_milestone_definitions;
create policy "public read active steward milestones" on public.steward_milestone_definitions
for select using (is_active = true);

drop policy if exists "stewards read own steward profile" on public.vnb_stewards;
create policy "stewards read own steward profile" on public.vnb_stewards
for select using (auth.uid() = user_id);

drop policy if exists "stewards read own referral codes" on public.steward_referral_codes;
create policy "stewards read own referral codes" on public.steward_referral_codes
for select using (auth.uid() = steward_id);

drop policy if exists "stewards read own payouts" on public.steward_payouts;
create policy "stewards read own payouts" on public.steward_payouts
for select using (auth.uid() = steward_id);

drop policy if exists "stewards read own commissions" on public.steward_commissions;
create policy "stewards read own commissions" on public.steward_commissions
for select using (auth.uid() = steward_id);

drop policy if exists "stewards read own milestone awards" on public.steward_milestone_awards;
create policy "stewards read own milestone awards" on public.steward_milestone_awards
for select using (auth.uid() = steward_id);

drop policy if exists "stewards read own reward ledger" on public.steward_reward_ledger;
create policy "stewards read own reward ledger" on public.steward_reward_ledger
for select using (auth.uid() = steward_id);

drop policy if exists "admins full steward_waitlist" on public.steward_waitlist;
create policy "admins full steward_waitlist" on public.steward_waitlist
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

drop policy if exists "admins full vnb_stewards" on public.vnb_stewards;
create policy "admins full vnb_stewards" on public.vnb_stewards
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

drop policy if exists "admins full steward_referral_codes" on public.steward_referral_codes;
create policy "admins full steward_referral_codes" on public.steward_referral_codes
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

drop policy if exists "admins full steward_payouts" on public.steward_payouts;
create policy "admins full steward_payouts" on public.steward_payouts
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

drop policy if exists "admins full steward_commissions" on public.steward_commissions;
create policy "admins full steward_commissions" on public.steward_commissions
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

drop policy if exists "admins full steward_milestone_definitions" on public.steward_milestone_definitions;
create policy "admins full steward_milestone_definitions" on public.steward_milestone_definitions
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

drop policy if exists "admins full steward_milestone_awards" on public.steward_milestone_awards;
create policy "admins full steward_milestone_awards" on public.steward_milestone_awards
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

drop policy if exists "admins full steward_reward_ledger" on public.steward_reward_ledger;
create policy "admins full steward_reward_ledger" on public.steward_reward_ledger
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

insert into public.steward_milestone_definitions (slug, name, description, measurement_window, required_successful_orders, reward_type, reward_value, is_active)
values
  ('weekly-5-sales', '5 Weekly Sales', 'Recognition inside the VNB Steward community for five successful attributed purchases in a week.', 'weekly', 5, 'recognition', 'community-recognition', true),
  ('weekly-10-sales', '10 Weekly Sales', 'Eligibility for a product reward after ten successful attributed purchases in a week.', 'weekly', 10, 'free_product', 'product-reward', true),
  ('weekly-20-sales', '20 Weekly Sales', 'Exclusive brand merchandise and ambassador review after twenty successful attributed purchases in a week.', 'weekly', 20, 'merchandise', 'exclusive-merchandise', true)
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  measurement_window = excluded.measurement_window,
  required_successful_orders = excluded.required_successful_orders,
  reward_type = excluded.reward_type,
  reward_value = excluded.reward_value,
  is_active = excluded.is_active;

create or replace function public.resolve_active_steward_referral_code(p_code text)
returns table (
  steward_id uuid,
  code text,
  display_name text,
  commission_tier text,
  commission_rate numeric
)
language sql
stable
security definer
set search_path = public
as $$
  select
    s.user_id,
    rc.code,
    s.display_name,
    s.commission_tier,
    s.commission_rate
  from public.steward_referral_codes rc
  join public.vnb_stewards s on s.user_id = rc.steward_id
  where rc.code = public.normalize_referral_code(p_code)
    and rc.status = 'active'
    and s.status = 'active'
  limit 1;
$$;

create or replace function public.finalize_payment_attempt(
  p_reference text,
  p_paystack_status text default '',
  p_verified_at timestamptz default public.now_utc()
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_attempt public.payment_attempts%rowtype;
  v_order public.orders%rowtype;
  v_item jsonb;
  v_product public.products%rowtype;
  v_quantity integer;
  v_commission_rate numeric(5, 4);
begin
  select *
  into v_attempt
  from public.payment_attempts
  where reference = p_reference
  for update;

  if not found then
    raise exception 'Payment reference not found.';
  end if;

  if v_attempt.order_id is not null then
    select * into v_order from public.orders where id = v_attempt.order_id;
    return v_order;
  end if;

  insert into public.orders (
    user_id,
    email,
    first_name,
    last_name,
    phone,
    address,
    city,
    state,
    zip_code,
    country,
    subtotal,
    shipping,
    tax,
    total,
    status,
    payment_provider,
    payment_reference,
    payment_currency,
    payment_status,
    paid_at,
    notes,
    steward_id,
    referral_code,
    referral_snapshot,
    commissionable_subtotal
  )
  values (
    v_attempt.user_id,
    v_attempt.email,
    v_attempt.first_name,
    v_attempt.last_name,
    v_attempt.phone,
    v_attempt.address,
    v_attempt.city,
    v_attempt.state,
    v_attempt.zip_code,
    v_attempt.country,
    v_attempt.subtotal,
    v_attempt.shipping,
    v_attempt.tax,
    v_attempt.total,
    'processing',
    'paystack',
    v_attempt.reference,
    v_attempt.currency,
    'paid',
    coalesce(p_verified_at, public.now_utc()),
    v_attempt.notes,
    v_attempt.steward_id,
    v_attempt.referral_code,
    v_attempt.referral_snapshot,
    v_attempt.subtotal
  )
  returning * into v_order;

  for v_item in
    select * from jsonb_array_elements(v_attempt.cart_snapshot)
  loop
    v_quantity := coalesce((v_item ->> 'quantity')::integer, 0);

    select *
    into v_product
    from public.products
    where id = (v_item ->> 'product_id')::bigint
      and is_active = true
    for update;

    if not found then
      raise exception 'Product no longer exists for reference %.', p_reference;
    end if;

    if v_quantity <= 0 then
      raise exception 'Invalid quantity supplied for product %.', v_product.name;
    end if;

    if v_product.stock_quantity < v_quantity then
      raise exception 'Insufficient stock for %.', v_product.name;
    end if;

    insert into public.order_items (
      order_id,
      product_id,
      product_name,
      product_sku,
      quantity,
      size,
      color,
      price,
      subtotal
    )
    values (
      v_order.id,
      v_product.id,
      coalesce(v_item ->> 'product_name', v_product.name),
      coalesce(v_item ->> 'product_sku', coalesce(v_product.sku, '')),
      v_quantity,
      coalesce(v_item ->> 'size', ''),
      coalesce(v_item ->> 'color', ''),
      (v_item ->> 'price')::numeric,
      (v_item ->> 'subtotal')::numeric
    );

    update public.products
    set stock_quantity = stock_quantity - v_quantity
    where id = v_product.id;
  end loop;

  if v_attempt.steward_id is not null and exists (
    select 1
    from public.vnb_stewards s
    where s.user_id = v_attempt.steward_id
      and s.status = 'active'
  ) then
    v_commission_rate := coalesce(
      nullif(v_attempt.referral_snapshot ->> 'commission_rate', '')::numeric,
      (select s.commission_rate from public.vnb_stewards s where s.user_id = v_attempt.steward_id),
      0.1000
    );

    insert into public.steward_commissions (
      steward_id,
      order_id,
      referral_code,
      basis_amount,
      commission_rate,
      commission_amount,
      status
    )
    values (
      v_attempt.steward_id,
      v_order.id,
      v_attempt.referral_code,
      v_attempt.subtotal,
      v_commission_rate,
      round(v_attempt.subtotal * v_commission_rate, 2),
      'pending'
    )
    on conflict (order_id) do nothing;
  end if;

  update public.payment_attempts
  set
    order_id = v_order.id,
    status = 'success',
    paystack_status = coalesce(nullif(p_paystack_status, ''), paystack_status),
    verified_at = coalesce(p_verified_at, public.now_utc())
  where id = v_attempt.id;

  return v_order;
end;
$$;
