-- Steward applications (post-account) + brand-ambassador invite codes
-- Run after 04_affiliates.sql
-- Emails: use Supabase Database Webhooks or your API on insert into steward_applications
--         and when payment_attempts are created with a referral_code (checkout worker).

create table if not exists public.steward_invite_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  invite_type text not null default 'brand_ambassador'
    check (invite_type in ('brand_ambassador')),
  note text not null default '',
  redeemed boolean not null default false,
  redeemed_by_user_id uuid references auth.users(id) on delete set null,
  redeemed_at timestamptz,
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

drop trigger if exists trg_steward_invite_codes_prepare on public.steward_invite_codes;
create trigger trg_steward_invite_codes_prepare
before insert or update on public.steward_invite_codes
for each row execute procedure public.prepare_steward_referral_code();

drop trigger if exists trg_steward_invite_codes_updated_at on public.steward_invite_codes;
create trigger trg_steward_invite_codes_updated_at before update on public.steward_invite_codes
for each row execute procedure public.set_updated_at();

create table if not exists public.steward_applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  application_type text not null
    check (application_type in ('affiliate', 'brand_ambassador')),
  ambassador_invite_code text not null default '',
  status text not null default 'submitted'
    check (status in ('submitted', 'under_review', 'approved', 'rejected')),
  submitted_at timestamptz not null default public.now_utc(),
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc(),
  constraint steward_applications_user_unique unique (user_id)
);

drop trigger if exists trg_steward_applications_updated_at on public.steward_applications;
create trigger trg_steward_applications_updated_at before update on public.steward_applications
for each row execute procedure public.set_updated_at();

create index if not exists idx_steward_invite_codes_redeemed on public.steward_invite_codes(redeemed);
create index if not exists idx_steward_applications_user on public.steward_applications(user_id);
create index if not exists idx_steward_applications_status on public.steward_applications(status);

alter table public.steward_invite_codes enable row level security;
alter table public.steward_applications enable row level security;

drop policy if exists "admins full steward_invite_codes" on public.steward_invite_codes;
create policy "admins full steward_invite_codes" on public.steward_invite_codes
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

drop policy if exists "users read own steward_applications" on public.steward_applications;
create policy "users read own steward_applications" on public.steward_applications
for select using (auth.uid() = user_id);

drop policy if exists "admins full steward_applications" on public.steward_applications;
create policy "admins full steward_applications" on public.steward_applications
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

-- Allow anonymous + signed-in shoppers to validate a steward code at checkout (no row data leak beyond resolution).
grant execute on function public.resolve_active_steward_referral_code(text) to anon, authenticated;

create or replace function public.submit_steward_application(
  p_application_type text,
  p_ambassador_invite_code text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_email text;
  v_meta jsonb;
  v_first text;
  v_last text;
  v_full text;
  v_norm_invite text;
  v_invite_id bigint;
  v_phone text;
  v_location text;
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;

  if exists (select 1 from public.vnb_stewards s where s.user_id = v_uid) then
    raise exception 'already_steward';
  end if;

  if exists (select 1 from public.steward_applications a where a.user_id = v_uid) then
    raise exception 'already_applied';
  end if;

  if p_application_type not in ('affiliate', 'brand_ambassador') then
    raise exception 'invalid_application_type';
  end if;

  if p_application_type = 'brand_ambassador' then
    v_norm_invite := public.normalize_referral_code(p_ambassador_invite_code);
    if v_norm_invite = '' then
      raise exception 'ambassador_code_required';
    end if;

    select c.id into v_invite_id
    from public.steward_invite_codes c
    where c.code = v_norm_invite
      and c.invite_type = 'brand_ambassador'
      and c.redeemed = false
    for update;

    if v_invite_id is null then
      raise exception 'invalid_ambassador_code';
    end if;

    update public.steward_invite_codes
    set
      redeemed = true,
      redeemed_by_user_id = v_uid,
      redeemed_at = public.now_utc(),
      updated_at = public.now_utc()
    where id = v_invite_id;
  else
    if nullif(trim(p_ambassador_invite_code), '') is not null then
      raise exception 'ambassador_code_forbidden_for_affiliate';
    end if;
  end if;

  select u.email, u.raw_user_meta_data into v_email, v_meta
  from auth.users u
  where u.id = v_uid;

  select p.phone, p.location into v_phone, v_location
  from public.user_profiles p
  where p.user_id = v_uid;

  v_first := coalesce(v_meta ->> 'first_name', '');
  v_last := coalesce(v_meta ->> 'last_name', '');
  v_full := trim(v_first || ' ' || v_last);

  insert into public.steward_applications (user_id, application_type, ambassador_invite_code, status)
  values (
    v_uid,
    p_application_type,
    case
      when p_application_type = 'brand_ambassador'
      then public.normalize_referral_code(p_ambassador_invite_code)
      else ''
    end,
    'submitted'
  );

  insert into public.steward_waitlist (
    full_name,
    email,
    phone,
    location,
    background,
    message,
    status,
    converted_user_id
  )
  values (
    coalesce(nullif(v_full, ''), split_part(v_email, '@', 1)),
    v_email,
    coalesce(v_phone, ''),
    coalesce(v_location, ''),
    'VNB Steward application (signed-in account). Type: ' || p_application_type,
    'Submitted from account. user_id=' || v_uid::text,
    'joined',
    v_uid
  )
  on conflict (email) do update set
    full_name = excluded.full_name,
    phone = excluded.phone,
    location = excluded.location,
    background = excluded.background,
    message = excluded.message,
    converted_user_id = excluded.converted_user_id,
    updated_at = public.now_utc();

  return jsonb_build_object('ok', true);
end;
$$;

grant execute on function public.submit_steward_application(text, text) to authenticated;

-- Let stewards read minimal order + line items for commissions attributed to them (dashboard).
drop policy if exists "stewards read attributed orders" on public.orders;
create policy "stewards read attributed orders" on public.orders
for select using (
  exists (
    select 1 from public.steward_commissions sc
    where sc.order_id = orders.id and sc.steward_id = auth.uid()
  )
);

drop policy if exists "stewards read order_items for attributed orders" on public.order_items;
create policy "stewards read order_items for attributed orders" on public.order_items
for select using (
  exists (
    select 1 from public.steward_commissions sc
    where sc.order_id = order_items.order_id and sc.steward_id = auth.uid()
  )
);

-- Optional: insert brand-ambassador invite codes (admin SQL or admin panel).
-- insert into public.steward_invite_codes (code, note) values ('VNB-INV-001', 'Issued to Jane');

-- Emails (implement outside Postgres):
-- 1) Applicant confirmation: Supabase Database Webhook on steward_applications INSERT → your email API.
-- 2) Steward notified when code used: in your checkout worker, after creating payment_attempt with referral_code,
--    load vnb_stewards by steward_id and send email (or call Supabase Edge Function).
