-- VNB Supabase schema (Django migration target)
-- Run in Supabase SQL editor in this order:
-- 1) this file
-- 2) create at least one auth user, then insert into admin_users

create extension if not exists pgcrypto;

-- -----------------------------
-- Helpers
-- -----------------------------
create or replace function public.now_utc()
returns timestamptz
language sql
stable
as $$
  select timezone('utc', now());
$$;

create or replace function public.generate_order_number()
returns text
language sql
stable
as $$
  select 'VNB-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = public.now_utc();
  return new;
end;
$$;

-- -----------------------------
-- Core catalog
-- -----------------------------
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text not null default '',
  image_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete cascade,
  name text not null,
  slug text not null unique,
  description text not null default '',
  price numeric(10, 2) not null check (price >= 0),
  image_url text,
  is_active boolean not null default true,
  is_featured boolean not null default false,
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  sku text unique,
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image_url text not null,
  alt_text text not null default '',
  is_primary boolean not null default false,
  "order" integer not null default 0,
  created_at timestamptz not null default public.now_utc()
);

create table if not exists public.product_colors (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  name text not null,
  hex_code text not null,
  is_available boolean not null default true,
  unique(product_id, name)
);

create table if not exists public.product_sizes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  size text not null,
  is_available boolean not null default true,
  unique(product_id, size)
);

create table if not exists public.product_details (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  detail text not null,
  "order" integer not null default 0
);

-- -----------------------------
-- Comms / lead capture
-- -----------------------------
create table if not exists public.newsletters (
  id bigint generated by default as identity primary key,
  email text not null unique,
  subscribed_at timestamptz not null default public.now_utc(),
  is_active boolean not null default true
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null default '',
  subject text not null,
  message text not null,
  created_at timestamptz not null default public.now_utc(),
  is_read boolean not null default false
);

create table if not exists public.investment_inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  tier text not null check (tier in ('seed', 'growth', 'strategic', 'custom')),
  message text not null default '',
  created_at timestamptz not null default public.now_utc(),
  is_contacted boolean not null default false
);

-- -----------------------------
-- User profile + commerce
-- -----------------------------
create table if not exists public.user_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  title text not null default '',
  phone text not null default '',
  area_code text not null default '+1',
  birth_date date,
  company text not null default '',
  address text not null default '',
  address_continued text not null default '',
  city text not null default '',
  state text not null default '',
  zip_code text not null default '',
  zip_plus text not null default '',
  location text not null default 'United States',
  newsletter_subscribed boolean not null default false,
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

create table if not exists public.carts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  session_key text not null default '',
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  cart_id bigint not null references public.carts(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  size text not null default '',
  color text not null default '',
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc(),
  unique(cart_id, product_id, size, color)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  order_number text not null unique default public.generate_order_number(),
  email text not null,
  first_name text not null,
  last_name text not null,
  phone text not null,
  address text not null,
  city text not null,
  state text not null,
  zip_code text not null,
  country text not null,
  subtotal numeric(10, 2) not null,
  shipping numeric(10, 2) not null default 0,
  tax numeric(10, 2) not null default 0,
  total numeric(10, 2) not null,
  status text not null default 'pending' check (status in ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
  payment_provider text not null default '',
  payment_reference text unique,
  payment_currency text not null default 'USD',
  payment_status text not null default 'pending' check (payment_status in ('pending', 'paid', 'failed')),
  paid_at timestamptz,
  notes text not null default '',
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  product_sku text not null default '',
  quantity integer not null check (quantity > 0),
  size text not null default '',
  color text not null default '',
  price numeric(10, 2) not null,
  subtotal numeric(10, 2) not null
);

create table if not exists public.payment_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  order_id bigint unique references public.orders(id) on delete set null,
  reference text not null unique,
  access_code text not null default '',
  authorization_url text not null default '',
  email text not null,
  first_name text not null,
  last_name text not null,
  phone text not null,
  address text not null,
  city text not null,
  state text not null,
  zip_code text not null,
  country text not null,
  notes text not null default '',
  subtotal numeric(10, 2) not null,
  shipping numeric(10, 2) not null default 0,
  tax numeric(10, 2) not null default 0,
  total numeric(10, 2) not null,
  currency text not null default 'USD',
  status text not null default 'initialized' check (status in ('initialized', 'pending', 'success', 'failed')),
  paystack_status text not null default '',
  cart_snapshot jsonb not null default '[]'::jsonb,
  cart_item_ids jsonb not null default '[]'::jsonb,
  verified_at timestamptz,
  created_at timestamptz not null default public.now_utc(),
  updated_at timestamptz not null default public.now_utc()
);

-- -----------------------------
-- Admin users table + helper
-- -----------------------------
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default public.now_utc()
);

create or replace function public.is_admin(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.admin_users where user_id = uid);
$$;

-- -----------------------------
-- Indexes
-- -----------------------------
create index if not exists idx_products_category_active on public.products(category_id, is_active);
create index if not exists idx_products_slug on public.products(slug);
create index if not exists idx_orders_user on public.orders(user_id);
create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_contact_messages_created_at on public.contact_messages(created_at desc);
create index if not exists idx_investment_inquiries_created_at on public.investment_inquiries(created_at desc);

-- -----------------------------
-- Triggers for updated_at
-- -----------------------------
drop trigger if exists trg_categories_updated_at on public.categories;
create trigger trg_categories_updated_at before update on public.categories
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_products_updated_at on public.products;
create trigger trg_products_updated_at before update on public.products
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_user_profiles_updated_at on public.user_profiles;
create trigger trg_user_profiles_updated_at before update on public.user_profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_carts_updated_at on public.carts;
create trigger trg_carts_updated_at before update on public.carts
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_cart_items_updated_at on public.cart_items;
create trigger trg_cart_items_updated_at before update on public.cart_items
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at before update on public.orders
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_payment_attempts_updated_at on public.payment_attempts;
create trigger trg_payment_attempts_updated_at before update on public.payment_attempts
for each row execute procedure public.set_updated_at();

-- -----------------------------
-- RLS
-- -----------------------------
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.product_colors enable row level security;
alter table public.product_sizes enable row level security;
alter table public.product_details enable row level security;
alter table public.newsletters enable row level security;
alter table public.contact_messages enable row level security;
alter table public.investment_inquiries enable row level security;
alter table public.user_profiles enable row level security;
alter table public.carts enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payment_attempts enable row level security;
alter table public.admin_users enable row level security;

-- Public read catalog
create policy "public read active categories" on public.categories
for select using (is_active = true);

create policy "public read active products" on public.products
for select using (is_active = true);

create policy "public read product images" on public.product_images
for select using (
  exists (
    select 1 from public.products p
    where p.id = product_images.product_id and p.is_active = true
  )
);

create policy "public read product colors" on public.product_colors
for select using (
  exists (
    select 1 from public.products p
    where p.id = product_colors.product_id and p.is_active = true
  )
);

create policy "public read product sizes" on public.product_sizes
for select using (
  exists (
    select 1 from public.products p
    where p.id = product_sizes.product_id and p.is_active = true
  )
);

create policy "public read product details" on public.product_details
for select using (
  exists (
    select 1 from public.products p
    where p.id = product_details.product_id and p.is_active = true
  )
);

-- Public inserts for lead capture
create policy "public insert newsletters" on public.newsletters
for insert with check (true);

create policy "public insert contact_messages" on public.contact_messages
for insert with check (true);

create policy "public insert investment_inquiries" on public.investment_inquiries
for insert with check (true);

-- User profile and own commerce records
create policy "users read own profile" on public.user_profiles
for select using (auth.uid() = user_id);
create policy "users update own profile" on public.user_profiles
for update using (auth.uid() = user_id);
create policy "users insert own profile" on public.user_profiles
for insert with check (auth.uid() = user_id);

create policy "users read own carts" on public.carts
for select using (auth.uid() = user_id);
create policy "users manage own carts" on public.carts
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "users read own cart_items" on public.cart_items
for select using (
  exists (select 1 from public.carts c where c.id = cart_items.cart_id and c.user_id = auth.uid())
);
create policy "users manage own cart_items" on public.cart_items
for all using (
  exists (select 1 from public.carts c where c.id = cart_items.cart_id and c.user_id = auth.uid())
) with check (
  exists (select 1 from public.carts c where c.id = cart_items.cart_id and c.user_id = auth.uid())
);

create policy "users read own orders" on public.orders
for select using (auth.uid() = user_id);

create policy "users read own order_items" on public.order_items
for select using (
  exists (select 1 from public.orders o where o.id = order_items.order_id and o.user_id = auth.uid())
);

create policy "users read own payment_attempts" on public.payment_attempts
for select using (auth.uid() = user_id);

-- Admin policies
create policy "admins full categories" on public.categories
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admins full products" on public.products
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admins full product_images" on public.product_images
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admins full product_colors" on public.product_colors
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admins full product_sizes" on public.product_sizes
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admins full product_details" on public.product_details
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admins full newsletters" on public.newsletters
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admins full contact_messages" on public.contact_messages
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admins full investment_inquiries" on public.investment_inquiries
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admins full user_profiles" on public.user_profiles
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admins full carts" on public.carts
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admins full cart_items" on public.cart_items
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admins full orders" on public.orders
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admins full order_items" on public.order_items
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admins full payment_attempts" on public.payment_attempts
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admins full admin_users" on public.admin_users
for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
